#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Mon Jun 18 17:53:26 2018

aggregate
@author: xinjiwang
"""


import operator
from pymongo import MongoClient
import pandas as pd
from collections import Counter
import os 
import time
start = time.time()

def sort_array(array):
    score = dict(Counter(array))
    return score

os.chdir('/Users/xinjiwang/Desktop/data')

client = MongoClient( host = 'tombraider.shopcade.com',port = 27031  )
db = client['lancaster']

print(db.collection_names())
names = db.collection_names()
collection = db.collections
coll1 = db.get_collection('trkelle2')


#load ={}
view = {}
click = {}
hover = {}
n = 0
#.sort([("ts", pymongo.ASCENDING)]).limit(10):
#agg = coll1.aggregate([
#        {"$match":{"tag":'product-load'}},
#        {"$group":{"_id":{"pid":"$data.pid",
#                          "scid":"$scid"},
#                   "sum":{"$sum":1}}},
#        {"$project":{"load":{"$concat":["$_id.pid","-","$_id.scid"]},
#                     "sum":1}}])
#load = [doc for doc in agg]

s = time.time()
agg = coll1.aggregate([
        {"$match":{"tag":{"$in":['dynamic-product-view',
                                 'list-product-view',
                                 'product-product-view',
                                 'button-product-view']}}},
        {"$group":{"_id":{"pid":"$data",
                          "scid":"$scid"},
                   "sum":{"$sum":1}}},
        {"$project":{"view":{"$concat":["$_id.pid","-","$_id.scid"]},
                     "sum":1}}],
    allowDiskUse = True)
view = [doc for doc in agg]
e = time.time()
print(s-e)

agg = coll1.aggregate([
        {"$match":{"tag":'product-click'}},
         {"$group":{"_id":{"pid":"$data.pid",
                          "scid":"$scid"},
                   "sum":{"$sum":1}}},
        {"$project":{"clcik":{"$concat":["$_id.pid","-","$_id.scid"]},
                     "sum":1}}],
     allowDiskUse = True)
click = [doc for doc in agg]
e = time.time()
print(s-e)
agg = coll1.aggregate([
        {"$match":{"tag":'p-hover'}},
        {"$group":{"_id":{"pid":"$data.pid",
                          "scid":"$scid"},
                   "sum":{"$sum":1}}},
        {"$project":{"hover":{"$concat":["$_id.pid","-","$_id.scid"]},
                     "sum":1}}],
     allowDiskUse = True)
hover = [doc for doc in agg]
e = time.time()
print(s-e)     
end = time.time()
print ('total time : ',end - start,'s' )

start = time.time()
#load_time = []
#pid_load = [] 
#for key in load.keys():
#    pid_load.append(key[0:24])
#load_time = sort_array(pid_load)

pid_view = [] 
for i in range(len(view)):
    pid_view.append(view[i]['view'][0:24])
view_time = sort_array(pid_view)


pid_click = [] 
for i in range(len(click)):
    pid_click.append(click[i]['_id']['pid'])
click_time = sort_array(pid_click)


pid_hover = [] 

for i in range(len(hover)):
    pid_hover.append(hover[i]['_id']['pid'])
hover_time = sort_array(pid_hover)

view_count  = []
click_count = []
hover_count = []

for pid in view_time.keys():
    if pid in pid_click:       
        click_count.append(click_time.get(pid))
    else:
        click_count.append(0)
for pid in view_time.keys():
    if pid in pid_hover:
        hover_count.append(hover_time.get(pid))
    else:
        hover_count.append(0)

data = pd.DataFrame({'pid':list(view_time.keys()),'view':list(view_time.values()),'hover':hover_count,'click':click_count}) 
end = time.time()
print ('load time : ',end - start,'s' )


data.to_csv('1monthdata.csv',index = False)
