#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Fri Jun 15 15:19:35 2018

@author: xinjiwang
"""

import operator
import pymongo
import numpy as np
from pymongo import MongoClient
import pandas as pd
from collections import Counter
import seaborn as sns
import os 
import datetime
import time
start = time.time()

def sort_array(array):
    score = dict(Counter(array))
    return score

os.chdir('/Users/xinjiwang/Desktop/data')

client = MongoClient( host = 'tombraider.shopcade.com',port = 27031  )
db = client['lancaster']

print(db.collection_names())
names = db.collection_names()
collection = db.collections
coll1 = db.get_collection('trkelle2')


load ={}
view = {}
click = {}
hover = {}
n = 0
#.sort([("ts", pymongo.ASCENDING)]).limit(10):
for doc in coll1.find({}).sort([("ts", pymongo.DESCENDING)]):
    n +=1
    if doc['tag'] ==  'product-load'and load.get(str(doc['data']['pid']+'-'+doc['scid'])) ==None :
        c = str(doc['data']['pid']+'-'+doc['scid'])
        load[c] = 1
    if doc['tag'] ==  'product-load' and load.get(str(doc['data']['pid']+'-'+doc['scid'])) != None :
        c = str(doc['data']['pid']+'-'+doc['scid'])
        load[c] +=  1   
    if doc['tag'] in  ['dynamic-product-view','list-product-view','product-product-view','button-product-view']  and view.get(str(doc['data']+'-'+doc['scid'])) ==None :
        c = str(doc['data']+'-'+doc['scid'])
        view[c] =1
    if doc['tag'] in  ['dynamic-product-view','list-product-view','product-product-view','button-product-view']  and view.get(str(doc['data']+'-'+doc['scid'])) !=None :
        c = str(doc['data']+'-'+doc['scid'])
        view[c] +=1  
    if doc['tag'] ==  'product-click'and click.get(str(doc['data']['pid']+'-'+doc['scid'])) ==None :
        c = str(doc['data']['pid']+'-'+doc['scid'])
        click[c] = 1
    if doc['tag'] ==  'product-click' and  click.get(str(doc['data']['pid']+'-'+doc['scid'])) !=None :
        c = str(doc['data']['pid']+'-'+doc['scid'])
        click[c] +=  1 
    if doc['tag'] ==  'p-hover'and  hover.get(str(doc['data']['pid']+'-'+doc['scid'])) ==None :
        c = str(doc['data']['pid']+'-'+doc['scid'])
        hover[c] = 1
    if doc['tag'] ==  'p-hover' and  hover.get(str(doc['data']['pid']+'-'+doc['scid'])) !=None :
        c = str(doc['data']['pid']+'-'+doc['scid'])
        hover[c] +=  1   
    if n % 50000 == 0:
        print(n)
        
end = time.time()
print ('total time : ',end - start,'s' )

start = time.time()
load_time = []
pid_load = [] 
for key in load.keys():
    pid_load.append(key[0:24])
load_time = sort_array(pid_load)

view_time = []
pid_view = [] 
for key in view.keys():
    pid_view.append(key[0:24])
view_time = sort_array(pid_view)


click_time = []
pid_click = [] 
for key in click.keys():
    pid_click.append(key[0:24])
click_time = sort_array(pid_click)


hover_time = []
pid_hover = [] 
for key in hover.keys():
    pid_hover.append(key[0:24])
hover_time = sort_array(pid_hover)

view_count  = []
click_count = []
hover_count = []
for pid in load_time.keys():
    if pid in pid_view:
        view_count.append(view_time.get(pid))
    else:
        view_count.append(0)
        
        
for pid in view_time.keys():
    if pid in pid_click:       
        click_count.append(click_time.get(pid))
    else:
        click_count.append(0)
for pid in view_time.keys():
    if pid in pid_hover:
        hover_count.append(hover_time.get(pid))
    else:
        hover_count.append(0)

data = pd.DataFrame({'pid':load_time.keys(),'load':load_time.values(),'view':view_count,'hover':hover_count,'click':click_count})    
end = time.time()
print ('load time : ',end - start,'s' )

data.to_csv('whole.csv')


        
    
        